tupla = ("Fernando","python","udemy")
print(tupla)
print(tupla[0])
print(tupla[1])
print(tupla[2])
print(tupla[0:2])
print(tupla[1:3])
print(len(tupla))
print(tupla*5)
print(tupla+tupla)
print(4 in tupla)
print("Fernando" in tupla)
lista = [1,4,"Fernando"]
print(lista)
tupla2 = tuple(lista)
print(tupla2)